### ISSUE TITLE
Error running dump_pfile_header

### ISSUE THREAD

**Issue by kyezhang** [njvack/pfile-tools#6]
Hi Nathan, 

I run into this error when running dump_pfile_header. BTW, I'm looking for the offsets and sizes of daptab and the exam info. 

(C:\Anaconda3) c:\Data\ADRC>dump_pfile_header -h
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\dump_pfile_header-script.py", line 11, in <module>
    load_entry_point('pfile-tools==0.5.0', 'console_scripts', 'dump_pfile_header
')()
  File "C:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 570, in
load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2755, in
 load_entry_point
    return ep.load()
  File "C:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2409, in
 load
    return self.resolve()
  File "C:\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2415, in
 resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named 'pfile_tools.scripts'

Sorry that I can't find how to fix the module name with my poor python knowledge. 

Thank you!
Kai

**Comment by njvack** [comment]
Hm... I suspect it's something about python 3 and module importing syntax. I'll try and take a peek.

**Comment by curtcorum** [comment]
FYI

I could not get dump_pfile_header to run under python 3. I did not try very hard, though. 

It does seem to run from 2.7.

Also it seems that 0.5.0 is not the latest (directly from pip). Using  sudo pip install --editable ./ from the cloned git tree did work fine.

Nice that it works with 26.002!

**Comment by njvack** [comment]
Hi,

I have basically zero time to maintain this project these days. I'm not gonna say I'll *never* check into to this but I don't have near-future plans to do it.

Sorry :/

**Comment by curtcorum** [comment]
Nate,

No worries!

Thanks for posting the code on github in the first place!

Curt

**Comment by sufkes** [comment]
I had the same problem as @kyezhang .  Using sudo pip install --editable ./ from the cloned git tree (as curtcorum suggested) seemed to fix this problem.
